apiVersion: v1
kind: Service
metadata:
  name: youtube-clone-app
  labels:
    app: youtube-clone-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: youtube-clone-app
